//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractManagementSystemDBEntities : DbContext
    {
        public ContractManagementSystemDBEntities()
            : base("name=ContractManagementSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAlertLog> tblAlertLogs { get; set; }
        public virtual DbSet<tblAlertSystem> tblAlertSystems { get; set; }
        public virtual DbSet<tblApprovalLog> tblApprovalLogs { get; set; }
        public virtual DbSet<tblApprovalMaster> tblApprovalMasters { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCategoryLog> tblCategoryLogs { get; set; }
        public virtual DbSet<tblClauseAudit> tblClauseAudits { get; set; }
        public virtual DbSet<tblClauseLog> tblClauseLogs { get; set; }
        public virtual DbSet<tblClauseMaster> tblClauseMasters { get; set; }
        public virtual DbSet<tblContractAudit> tblContractAudits { get; set; }
        public virtual DbSet<tblContractLog> tblContractLogs { get; set; }
        public virtual DbSet<tblContractMaster> tblContractMasters { get; set; }
        public virtual DbSet<tblContractModification> tblContractModifications { get; set; }
        public virtual DbSet<tblDeligationMatrix> tblDeligationMatrices { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblDepartmentLog> tblDepartmentLogs { get; set; }
        public virtual DbSet<tblDepartmentMapping> tblDepartmentMappings { get; set; }
        public virtual DbSet<tblSubCategory> tblSubCategories { get; set; }
        public virtual DbSet<tblSubCategoryLog> tblSubCategoryLogs { get; set; }
        public virtual DbSet<tblSubDepartment> tblSubDepartments { get; set; }
        public virtual DbSet<tblSubDepartmentLog> tblSubDepartmentLogs { get; set; }
        public virtual DbSet<tblTemplateAddendumLog> tblTemplateAddendumLogs { get; set; }
        public virtual DbSet<tblTemplateAmendment> tblTemplateAmendments { get; set; }
        public virtual DbSet<tblTemplateAudit> tblTemplateAudits { get; set; }
        public virtual DbSet<tblTemplateLog> tblTemplateLogs { get; set; }
        public virtual DbSet<tblTemplateMaster> tblTemplateMasters { get; set; }
        public virtual DbSet<tblUserLog> tblUserLogs { get; set; }
        public virtual DbSet<tblUserLogin> tblUserLogins { get; set; }
        public virtual DbSet<tblUserMaster> tblUserMasters { get; set; }
        public virtual DbSet<tblVariableData> tblVariableDatas { get; set; }
        public virtual DbSet<tblVariable> tblVariables { get; set; }
        public virtual DbSet<tblVendorLog> tblVendorLogs { get; set; }
        public virtual DbSet<tblVendorMaster> tblVendorMasters { get; set; }
        public virtual DbSet<tblDeligationLog> tblDeligationLogs { get; set; }
        public virtual DbSet<tblConfiguration> tblConfigurations { get; set; }
        public virtual DbSet<tblPlant> tblPlants { get; set; }
        public virtual DbSet<tblPlantLog> tblPlantLogs { get; set; }
        public virtual DbSet<tblApprovalEscalation> tblApprovalEscalations { get; set; }
    }
}
