//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlertSystem
    {
        public int AlertID { get; set; }
        public Nullable<int> ContractExpiryReminder1Date { get; set; }
        public string ContractExpiryReminder1Duration { get; set; }
        public Nullable<int> ContractExpiryReminder2Date { get; set; }
        public string ContractExpiryReminder2Duration { get; set; }
        public Nullable<int> ContractExpiryReminder3Date { get; set; }
        public string ContractExpiryReminder3Duration { get; set; }
        public Nullable<int> ContractExpiryReminder4Date { get; set; }
        public string ContractExpiryReminder4Duration { get; set; }
        public Nullable<int> ContractExpiryReminder5Date { get; set; }
        public string ContractExpiryReminder5Duration { get; set; }
        public string TemplateHod { get; set; }
        public string TemplateLegal { get; set; }
        public string TemplateFinance { get; set; }
        public string ContractHod { get; set; }
        public string ContractLegal { get; set; }
        public string ContractFinance { get; set; }
        public string EsclationHod { get; set; }
        public string EsclationLegal { get; set; }
        public string EsclationFinance { get; set; }
        public Nullable<int> AuditTemplateDate { get; set; }
        public string AuditTemplateDuration { get; set; }
        public Nullable<int> AuditContractDate { get; set; }
        public string AuditClauseDuration { get; set; }
        public Nullable<int> AuditClauseDate { get; set; }
        public string AuditContractDuration { get; set; }
        public Nullable<int> OldContractDate { get; set; }
        public string OldContractDuration { get; set; }
    }
}
