//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClauseMaster
    {
        public int ClauseClauseID { get; set; }
        public string ClauseClauseTitle { get; set; }
        public string ClauseClauseDescription { get; set; }
        public string ClauseClauseText { get; set; }
        public System.DateTime ClauseLastModified { get; set; }
        public string ClauseStatus { get; set; }
    
        public virtual tblClauseAudit tblClauseAudit { get; set; }
    }
}
