//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeligationMatrix
    {
        public int ID { get; set; }
        public Nullable<int> DeligateFrom { get; set; }
        public Nullable<int> DeligateTo { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}
