//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateAmendment
    {
        public int TempID { get; set; }
        public string Amendments { get; set; }
        public string Extension { get; set; }
        public string Termination { get; set; }
    }
}
