//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateMaster
    {
        public int TemplateID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Department { get; set; }
        public string SubDepartment { get; set; }
        public Nullable<int> TemplateSequence { get; set; }
        public Nullable<int> Initiator { get; set; }
        public string InitiatorStatus { get; set; }
        public string InitiatorComments { get; set; }
        public string Template { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateofInitiated { get; set; }
        public Nullable<System.DateTime> LastReviewed { get; set; }
        public Nullable<int> Approver1ID { get; set; }
        public string Approver1Draft { get; set; }
        public string Approver1Comments { get; set; }
        public string Approver1Status { get; set; }
        public Nullable<System.DateTime> Approver1ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver1ApprovedOn { get; set; }
        public Nullable<int> Approver2ID { get; set; }
        public string Approver2Draft { get; set; }
        public string Approver2Comments { get; set; }
        public string Approver2Status { get; set; }
        public Nullable<System.DateTime> Approver2ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver2ApprovedOn { get; set; }
        public Nullable<int> Approver3ID { get; set; }
        public string Approver3Draft { get; set; }
        public string Approver3Comments { get; set; }
        public string Approver3Status { get; set; }
        public Nullable<System.DateTime> Approver3ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver3ApprovedOn { get; set; }
        public Nullable<int> Approver4ID { get; set; }
        public string Approver4Draft { get; set; }
        public string Approver4Comments { get; set; }
        public string Approver4Status { get; set; }
        public Nullable<System.DateTime> Approver4ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver4ApprovedOn { get; set; }
        public Nullable<int> Approver5ID { get; set; }
        public string Approver5Draft { get; set; }
        public string Approver5Comments { get; set; }
        public string Approver5Status { get; set; }
        public Nullable<System.DateTime> Approver5ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver5ApprovedOn { get; set; }
        public Nullable<int> Approver6ID { get; set; }
        public string Approver6Draft { get; set; }
        public string Approver6Comments { get; set; }
        public string Approver6Status { get; set; }
        public Nullable<System.DateTime> Approver6ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver6ApprovedOn { get; set; }
        public Nullable<int> Approver7ID { get; set; }
        public string Approver7Draft { get; set; }
        public string Approver7Comments { get; set; }
        public string Approver7Status { get; set; }
        public Nullable<System.DateTime> Approver7ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver7ApprovedOn { get; set; }
        public Nullable<int> Approver8ID { get; set; }
        public string Approver8Draft { get; set; }
        public string Approver8Comments { get; set; }
        public string Approver8Status { get; set; }
        public Nullable<System.DateTime> Approver8ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver8ApprovedOn { get; set; }
        public Nullable<int> Approver9ID { get; set; }
        public string Approver9Draft { get; set; }
        public string Approver9Comments { get; set; }
        public string Approver9Status { get; set; }
        public Nullable<System.DateTime> Approver9ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver9ApprovedOn { get; set; }
        public Nullable<int> Approver10ID { get; set; }
        public string Approver10Draft { get; set; }
        public string Approver10Comments { get; set; }
        public string Approver10Status { get; set; }
        public Nullable<System.DateTime> Approver10ReceivedOn { get; set; }
        public Nullable<System.DateTime> Approver10ApprovedOn { get; set; }
        public string PendingFrom { get; set; }
        public string NextApprover { get; set; }
        public string RejectedBy { get; set; }
        public string Status { get; set; }
        public string InitiatorTemplate { get; set; }
        public Nullable<int> ReviewerID { get; set; }
        public string PhysicalCopyLocation { get; set; }
        public Nullable<System.DateTime> ReviewedOn { get; set; }
        public string ReviewedComments { get; set; }
    }
}
