//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorMaster
    {
        public int VendorVendorID { get; set; }
        public string VendorCorporateIdentificationNumber { get; set; }
        public string VendorVendorName { get; set; }
        public string VendorTypeofEntity { get; set; }
        public string VendorAuthorisedSignatory { get; set; }
        public string VendorRegisteredAddress { get; set; }
        public string VendorBranchOffice1 { get; set; }
        public string VendorBranchOffice2 { get; set; }
        public string VendorBranchOffice3 { get; set; }
        public string VendorBranchOffice4 { get; set; }
        public string VendorBranchOffice5 { get; set; }
    }
}
